services:
  - type: web
    name: telegram-bot
    env: node
    buildCommand: npm install
    startCommand: npx puppeteer install --path ./.cache/puppeteer && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 8080
