services:
  - type: web
    name: telegram-bot
    env: node
    buildCommand: |
      # Install Chrome dependencies
      apt-get update
      apt-get install -y wget gnupg2 apt-transport-https ca-certificates

      # Add Google Chrome repository
      wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list

      # Install Chrome
      apt-get update
      apt-get install -y google-chrome-stable

      # Verify Chrome installation
      google-chrome-stable --version

      # Set up Node.js and install dependencies
      export NODE_VERSION=16
      export CHROME_BIN=/usr/bin/google-chrome-stable
      npm ci
    startCommand: node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: CHROME_BIN
        value: /usr/bin/google-chrome-stable
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          name: telegram-bot
          envVarKey: RENDER_EXTERNAL_URL
    healthCheckPath: /
    autoDeploy: true
    plan: free
