services:
  - type: web
    name: telegram-bot
    env: node
    buildCommand: |
      # Create custom directory for Chrome
      mkdir -p /opt/chrome
      cd /opt/chrome

      # Download Chrome directly
      wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      echo "downloaded chrome"

      # Install dependencies
      apt-get update
      apt-get install -y ./google-chrome-stable_current_amd64.deb
      echo "installed chrome"

      # Verify installation
      echo "Chrome version:"
      /opt/chrome/google-chrome-stable --version

      # Set up Node.js and install dependencies
      export NODE_VERSION=16
      export CHROME_BIN=/opt/chrome/google-chrome-stable
      npm ci
    startCommand: node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: CHROME_BIN
        value: /opt/chrome/google-chrome-stable
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          name: telegram-bot
          envVarKey: RENDER_EXTERNAL_URL
    healthCheckPath: /
    autoDeploy: true
    plan: free
