services:
  - type: web
    name: telegram-bot
    env: node
    buildCommand: |
      apt-get update && apt-get install -y chromium
      export NODE_VERSION=16
      export CHROME_BIN=/usr/bin/google-chrome
      npm ci
    startCommand: node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: CHROME_BIN
        value: /usr/bin/google-chrome
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          name: telegram-bot
          envVarKey: RENDER_EXTERNAL_URL
    healthCheckPath: /
    autoDeploy: true
    plan: free
