services:
  - type: web
    name: telegram-bot
    env: node
    buildCommand: |
      apt-get update && apt-get install -y wget gnupg

      # Добавляем репозиторий Google Chrome
      wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list

      apt-get update && apt-get install -y google-chrome-stable

      # Проверяем установку
      which google-chrome-stable
      google-chrome-stable --version

      npm ci
    startCommand: node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: CHROME_BIN
        value: /opt/chrome/google-chrome-stable
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          name: telegram-bot
          envVarKey: RENDER_EXTERNAL_URL
    healthCheckPath: /
    autoDeploy: true
    plan: free
