services:
  - type: web
    name: telegram-bot
    env: node
    buildCommand: |
      # Install Chromium and verify
      apt-get update
      apt-get install -y chromium
      which chromium
      ls -l /usr/bin/chromium
      chromium --version

      # Set up Node.js and install dependencies
      export NODE_VERSION=16
      export CHROME_BIN=/usr/bin/chromium
      npm ci
    startCommand: node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: CHROME_BIN
        value: /usr/bin/chromium
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          name: telegram-bot
          envVarKey: RENDER_EXTERNAL_URL
    healthCheckPath: /
    autoDeploy: true
    plan: free
